#!/bin/bash

# install-arch.sh - Arch Linux Hyprland Installer
# Author: Generated by Agent
# Description: Automated installer for Arch Linux with Hyprland on specific hardware.

set -e # Exit on error
LOG_FILE="logs/install.log"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() {
    echo -e "${GREEN}[$(date +'%H:%M:%S')] $1${NC}" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}[$(date +'%H:%M:%S')] ERROR: $1${NC}" | tee -a "$LOG_FILE"
    exit 1
}

warn() {
    echo -e "${YELLOW}[$(date +'%H:%M:%S')] WARNING: $1${NC}" | tee -a "$LOG_FILE"
}

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    error "This script must be run as root."
fi

# Check for UEFI mode
if [ ! -d "/sys/firmware/efi/efivars" ]; then
    error "System is not booted in UEFI mode. This installer requires UEFI."
fi

# Check internet connection
log "Checking internet connection..."
if ! ping -c 1 archlinux.org &> /dev/null; then
    error "No internet connection. Please connect to the internet first."
fi

# Detect Partitions
log "Detecting partitions..."

# Find partition with label 'fydeos'
ROOT_PART=$(lsblk -o NAME,LABEL,PATH -nr | grep "fydeos" | head -n 1 | awk '{print $3}')
if [ -z "$ROOT_PART" ]; then
    error "Could not find partition with label 'fydeos'."
fi
log "Found Root partition (fydeos): $ROOT_PART"

# Find EFI partition (first vfat partition on the same disk usually, but we need to be careful)
# Heuristic: Find a partition on the same disk as ROOT_PART that is vfat and likely EFI.
# Assuming standard layout, looking for any partition with type vfat (often 1st or 2nd)
# Better: Look for partition with boot flag or type "EFI System"
# Since user specified "Otomatis mendeteksi partisi EFI Windows (filesystem vfat)", we search for vfat partitions.
DISK=$(lsblk -no pkname "$ROOT_PART" | head -n 1) # Get parent disk of root partition
DISK_PATH="/dev/$DISK"
log "Target Disk: $DISK_PATH"

# Try to find EFI partition on the same disk
EFI_PART=$(lsblk -o NAME,FSTYPE,PATH,PKNAME -nr | grep "$DISK" | grep "vfat" | head -n 1 | awk '{print $3}')

if [ -z "$EFI_PART" ]; then
    # Fallback: search system-wide for an EFI partition if not found on the same disk (unlikely but possible)
     EFI_PART=$(lsblk -o NAME,FSTYPE,PATH -nr | grep "vfat" | head -n 1 | awk '{print $3}')
     if [ -z "$EFI_PART" ]; then
        error "Could not find any EFI partition (vfat)."
     fi
     warn "EFI partition found on different disk or not clearly identified, using: $EFI_PART"
fi

log "Found EFI partition: $EFI_PART"

# Confirmation
echo -e "${YELLOW}"
echo "---------------------------------------------------"
echo "WARNING: DATA LOSS WARNING"
echo "The following partition will be FORMATTED as ext4:"
echo "  Routes: $ROOT_PART (Label: fydeos)"
echo ""
echo "The following partition will be MOUNTED as /boot:"
echo "  EFI:    $EFI_PART (Windows EFI)"
echo "---------------------------------------------------"
echo -e "${NC}"

read -p "Are you sure you want to continue? (yes/NO): " confirm
if [[ "$confirm" != "yes" ]]; then
    error "Installation aborted by user."
fi

# Formatting and Mounting
log "Formatting $ROOT_PART as ext4..."
mkfs.ext4 -F -L "arch_root" "$ROOT_PART"

log "Mounting partitions..."
mount "$ROOT_PART" /mnt

mkdir -p /mnt/boot
mount "$EFI_PART" /mnt/boot

# Install Base System
log "Installing base system (this may take a while)..."
pacstrap -K /mnt base linux linux-firmware vim nano intel-ucode amd-ucode

# Generate Fstab
log "Generating fstab..."
genfstab -U /mnt >> /mnt/etc/fstab

# Copy Scripts to /mnt
log "Copying installation scripts to /mnt..."
cp -r scripts /mnt/root/
cp -r logs /mnt/root/

# Make internal script executable
chmod +x /mnt/root/scripts/setup-chroot.sh

# Enter Chroot
log "Entering chroot environment..."
arch-chroot /mnt /root/scripts/setup-chroot.sh

log "Installation complete! You can now reboot."
echo "Don't forget to unmount: umount -R /mnt"
