#!/bin/bash

# scripts/setup-chroot.sh - Arch Linux Configuration (Revised)
# Description: Idempotent configuration script for dual-boot Hyprland setup.

set -e

LOG_FILE="/var/log/arch-hyprland-install.log"

log() {
    echo -e "\033[0;32m[$(date +'%H:%M:%S')] $1\033[0m" | tee -a "$LOG_FILE"
}

# --- System Configuration ---
log "Configuring Time and Locale..."
ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
hwclock --systohc

if ! grep -q "en_US.UTF-8 UTF-8" /etc/locale.gen; then
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen
fi
echo "LANG=en_US.UTF-8" > /etc/locale.conf

log "Setting Hostname..."
echo "arch-hypr" > /etc/hostname
if ! grep -q "arch-hypr" /etc/hosts; then
    {
        echo "127.0.0.1   localhost"
        echo "::1         localhost"
        echo "127.0.1.1   arch-hypr.localdomain arch-hypr"
    } >> /etc/hosts
fi

# --- User Management ---
USERNAME="JAWA"
PASSWORD="123"

log "Checking User: $USERNAME..."
if ! id "$USERNAME" &>/dev/null; then
    log "Creating user $USERNAME..."
    useradd -m -G wheel -s /bin/bash "$USERNAME"
    echo "$USERNAME:$PASSWORD" | chpasswd
    echo "root:$PASSWORD" | chpasswd
else
    log "User $USERNAME already exists. Skipping creation."
fi

log "Configuring Sudo..."
mkdir -p /etc/sudoers.d
if [ ! -f /etc/sudoers.d/wheel ]; then
    echo "%wheel ALL=(ALL:ALL) ALL" > /etc/sudoers.d/wheel
fi
chmod 440 /etc/sudoers.d/wheel

# --- Bootloader (GRUB UEFI) ---
log "Setting up Bootloader (GRUB)..."

# Idempotent package install
install_if_missing() {
    for pkg in "$@"; do
        if ! pacman -Qi "$pkg" &>/dev/null; then
            log "Installing $pkg..."
            pacman -S --noconfirm "$pkg"
        fi
    done
}

install_if_missing grub efibootmgr os-prober

# Ensure /boot/efi is mounted (safety check inside chroot)
if ! mountpoint -q /boot/efi; then
    log "Mounting EFI partition..."
    # We rely on /etc/fstab generated by install-arch.sh
    mount /boot/efi || log "WARNING: Could not mount /boot/efi. GRUB might fail."
fi

log "Installing GRUB to /boot/efi..."
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB --recheck

log "Configuring GRUB for Dual Boot..."
# Enable os-prober in /etc/default/grub
if grep -q "GRUB_DISABLE_OS_PROBER" /etc/default/grub; then
    sed -i 's/.*GRUB_DISABLE_OS_PROBER=.*/GRUB_DISABLE_OS_PROBER=false/' /etc/default/grub
else
    echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
fi

grub-mkconfig -o /boot/grub/grub.cfg

# --- Package Installation ---
log "Installing System Packages..."
PACKAGES=(
    base-devel git sudo networkmanager hyprland waybar kitty rofi-wayland
    dolphin sddm pipewire pipewire-pulse wireplumber wl-clipboard
    grim slurp fastfetch xdg-desktop-portal-hyprland neovim curl wget
    firefox ttf-font-awesome noto-fonts-emoji
)

install_if_missing "${PACKAGES[@]}"

# --- Services ---
log "Enabling Services..."
systemctl enable NetworkManager || true
systemctl enable sddm || true

# --- AUR Helper (paru) ---
if ! command -v paru &>/dev/null; then
    log "Installing Paru..."
    su - "$USERNAME" -c "git clone https://aur.archlinux.org/paru.git /home/$USERNAME/paru"
    su - "$USERNAME" -c "cd /home/$USERNAME/paru && makepkg -si --noconfirm"
    rm -rf "/home/$USERNAME/paru"
else
    log "Paru already installed. Skipping."
fi

# --- Dotfiles ---
DOTFILES_DIR="/home/$USERNAME/shell"
log "Checking Dotfiles..."
if [ ! -d "$DOTFILES_DIR" ]; then
    log "Cloning Caelestia shell dotfiles..."
    su - "$USERNAME" -c "git clone https://github.com/caelestia-dots/shell $DOTFILES_DIR"
    
    # Run installer if present
    if [ -f "$DOTFILES_DIR/install.sh" ]; then
        log "Running dotfiles installer..."
        su - "$USERNAME" -c "cd $DOTFILES_DIR && chmod +x install.sh && ./install.sh"
    elif [ -f "$DOTFILES_DIR/setup.sh" ]; then
        su - "$USERNAME" -c "cd $DOTFILES_DIR && chmod +x setup.sh && ./setup.sh"
    fi
else
    log "Dotfiles already present at $DOTFILES_DIR. Skipping clone."
fi

log "Setup Complete inside Chroot!"
exit 0
