#!/bin/bash

# scripts/setup-chroot.sh - Arch Linux Configuration
# Author: Generated by Agent
# Description: Configuration script running inside the chroot environment.

set -e
LOG_FILE="/root/logs/setup.log"
mkdir -p /root/logs

log() {
    echo -e "\033[0;32m[$(date +'%H:%M:%S')] $1\033[0m" | tee -a "$LOG_FILE"
}

error() {
    echo -e "\033[0;31m[$(date +'%H:%M:%S')] ERROR: $1\033[0m" | tee -a "$LOG_FILE"
    exit 1
}

# --- System Configuration ---
log "Setting Timezone..."
ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
hwclock --systohc

log "Setting Locale..."
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

log "Setting Hostname..."
echo "arch-hypr" > /etc/hostname
echo "127.0.0.1   localhost" >> /etc/hosts
echo "::1         localhost" >> /etc/hosts
echo "127.0.1.1   arch-hypr.localdomain arch-hypr" >> /etc/hosts

# --- User Management ---
log "Setting Root Password..."
echo "root:123" | chpasswd

log "Creating User JAWA..."
useradd -m -G wheel -s /bin/bash JAWA
echo "JAWA:123" | chpasswd

log "Configuring Sudo..."
echo "%wheel ALL=(ALL:ALL) ALL" >> /etc/sudoers.d/wheel # Simpler way to enable wheel group

# --- Bootloader ---
log "Installing Bootloader (GRUB)..."
pacman -S --noconfirm grub efibootmgr os-prober

log "Installing GRUB to EFI partition..."
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB

log "Configuring GRUB..."
# Enable os-prober
sed -i 's/#GRUB_DISABLE_OS_PROBER=false/GRUB_DISABLE_OS_PROBER=false/' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

# --- Package Installation ---
log "Installing Packages..."
PACKAGES=(
    base-devel
    git
    networkmanager
    hyprland
    waybar
    kitty
    rofi-wayland
    dolphin
    sddm
    pipewire
    pipewire-pulse
    wireplumber
    wl-clipboard
    grim
    slurp
    fastfetch
    xdg-desktop-portal-hyprland
    neovim
    curl
    wget
    firefox # Browser needed usually
    ttf-font-awesome # Fonts usually needed for waybar
    noto-fonts-emoji # Fonts usually needed for emojis
)

pacman -S --noconfirm "${PACKAGES[@]}"

# --- Services ---
log "Enabling Services..."
systemctl enable NetworkManager
systemctl enable sddm

# --- AUR Helper (paru) ---
log "Installing Paru (AUR Helper)..."

# Switch to user JAWA to build stuff
su - JAWA -c "git clone https://aur.archlinux.org/paru.git /home/JAWA/paru"
su - JAWA -c "cd /home/JAWA/paru && makepkg -si --noconfirm"
rm -rf /home/JAWA/paru

# --- Dotfiles ---
log "Setting up Caelestia Shell..."
su - JAWA -c "git clone https://github.com/caelestia-dots/shell /home/JAWA/shell"
# Assuming the installer needs to be run.
# The user request says: "Menjalankan installer shell tersebut sebagai user JAWA"
# We need to find the installer script name inside that repo. usually install.sh or similar.
# Checking repo structure via clone first is safer, but I can't clone here on host properly to check.
# I will assume standard practice or try to run what's common.
# Based on request: "install-arch.sh sebagai entry point utama" -> this is MY script.
# "Dotfiles: Installer harus ... Clone repo ... Menjalankan installer shell tersebut"
# I'll add a check or try to identify the script.
# Let's assume it has an install script.

# Since I can't check the repo content now, I'll log a warning if script not found, or try standard names.
# Commonly used: install.sh, setup.sh.
log "Running dotfiles installer..."
if [ -f "/home/JAWA/shell/install.sh" ]; then
    su - JAWA -c "cd /home/JAWA/shell && ./install.sh"
elif [ -f "/home/JAWA/shell/setup.sh" ]; then
    su - JAWA -c "cd /home/JAWA/shell && ./setup.sh"
else
    # Check if there is any .sh file and try to run it if it looks like an installer?
    # Or just warn.
    log "WARNING: Could not find obvious install script in Caelestia shell repo. You might need to run it manually."
    # List files to log for debug
    ls -F /home/JAWA/shell >> "$LOG_FILE"
fi

log "Setup Complete!"
exit 0
